#ifndef SYSTEM_INFORMATION_HPP
#define SYSTEM_INFORMATION_HPP

#define WNDH 920
#define WNDW 1408
#define FRAME_RATE 100
#define RENDER_COMPENSATION 3.0f / 4.0f
#define PX_PER_M 1
#define M_PER_PX 1 / PX_PER_M
#define SECONDS_PER_EARTH_YEAR 3.15576e7
#define EARTH_YEAR_PER_SECOND 1 / SECONDS_PER_EARTH_YEAR
//#define YEARS_PER_S 0.1


#endif